name: Morevanillaitems
version: '${project.version}'
main: morevanillaitems.distriful5061.github.com.morevanillaitems.Morevanillaitems
api-version: 1.18
authors: [ distriful5061 ]
description: aiueo
depend:
  -https://github.com/IPVP-MC/canvas
  -https://github.com/tr7zw/Item-NBT-API/
commands:
  craft:
    description: craft
  enderchest:
    aliases: [e]
    description: Enderchest