name: Morevanillaitems
version: '${project.version}'
main: morevanillaitems.distriful5061.github.com.morevanillaitems.Morevanillaitems
api-version: 1.18
authors: [ distriful5061 ]
description: aiueo
commands:
  enderchest:
    aliases: [e]
    description: Enderchest
  hp:
    description: send ur hp
  test:
    description: a
permissions:
  morevanillaitems.*:
    description: astarisuku
    default: op
    children:
      morevanillaitems.commands.enderchest: true
      morevanillaitems.commands.hp: true
  morevanillaitems.commands.enderchest:
    description: ennda-tixesuto
    default: true
  morevanillaitems.commands.hp:
    description: hp
    default: op
  morevanillaitems.commands.test:
    description: test
    default: op